# Generated by Django 4.1 on 2022-08-25 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_post', models.CharField(max_length=100, verbose_name='Título')),
                ('data_post', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('conteudo_post', models.TextField(verbose_name='Conteúdo')),
                ('excerto_post', models.TextField(verbose_name='Excerto')),
                ('imagem_post', models.URLField(blank=True, null=True)),
                ('publicado_post', models.BooleanField(default=False)),
                ('autor_post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categoria_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.categoria')),
            ],
        ),
    ]
